### ISSUE TITLE
Loop1之后出现No Tasks与Quit elective loop

### ISSUE THREAD

**Issue by baixiaosen** [Hovennnnn/PKUAutoElective#1]
### Check List

- [√] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [√] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [√] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [√] \( run `python3 --version` )
AutoElective version: [√] \( run `python3 main.py --version` )

### Config

[client]

supply_cancel_page = 1
refresh_interval = 5
random_deviation = 0.2
iaaa_client_timeout = 30
elective_client_timeout = 60
elective_client_pool_size = 5
elective_client_max_life = 600
login_loop_interval = 2
print_mutex_rules = true
debug_print_request = false
debug_dump_request = false

[monitor]

host = 127.0.0.1
port = 7074

;---------------- course ----------------;
 [course:english_1]
;
 name = 英语散文选读：16世纪至19世纪浪漫主义时期
 class = 3
 school = 英语语言文学系

 [course:english_2]
;
 name = 英语散文选读：16世纪至19世纪浪漫主义时期
 class = 1
 school = 英语语言文学系

 [course:english_3]
;
 name = 英语散文选读：16世纪至19世纪浪漫主义时期
 class = 4
 school = 英语语言文学系

 [course:english_4]
;
 name = 英语散文选读：16世纪至19世纪浪漫主义时期
 class = 2
 school = 英语语言文学系

 [course:mayuan]
;
 name = 马克思主义基本原理概论
 class = 2
 school = 马克思主义学院

 [course:piping]
;
 name = 当代文学与文化批评
 class = 1
 school = 中国语言文学系
（monitor和其余部分都是默认的）

### Issue Description
如题，我运行main.py之后，只进行了一个循环（Loop1）之后显示NoTasks以及Quit elective和Quit IAAA，不知道该怎么解决。此前的环境配置应该无误

**Comment by baixiaosen** [comment]
![P8YUS$Y3$DM 605C1X)RAOP](https://github.com/Hovennnnn/PKUAutoElective/assets/160398065/c4896162-999e-47ce-a073-4402982ec892)

**Comment by Hovennnnn** [comment]
请确认一下你的config文件的路径。
因为你执行的是`python main.py`，所以默认采用项目当前路径下的config.ini文件的配置。
如果需要指定config文件的路径，请使用`python main.py -c config文件路径`

**Comment by baixiaosen** [comment]
感谢告知！但我指定config文件路径后仍然如此，问题还是没有解决

**Comment by Hovennnnn** [comment]
抱歉，根据前面的信息，我目前没有办法复现你的问题，请根据Readme再确认一遍流程。

**Comment by TimothyWang-Tech** [comment]
感觉是course部分写的不规范，例如course每行前面有空格，或者奇怪的符号导致被注释掉了，如果name class school前面有空格会导致不能被识别
