### ISSUE TITLE
请问这是否是在运行？我应该怎么看课程是否已抢到？

### ISSUE THREAD

**Issue by Zrmmm** [Hovennnnn/PKUAutoElective#3]

**Comment by Zrmmm** [comment]
![Uploading 3eab51cd21780a73d895ab9fd1a0c9d.png…]()

**Comment by Zrmmm** [comment]
![3eab51cd21780a73d895ab9fd1a0c9d](https://github.com/user-attachments/assets/2e0ec6ef-a811-4e09-833e-6c1665816c45)

**Comment by Hovennnnn** [comment]
是的，这就是在运行，No course available表示目前要选的课没有名额。
选上了的会显示Elected，然后接着刷没选上的课

**Comment by Hovennnnn** [comment]
closed
