### ISSUE TITLE
选课网现在会封ip，请问该怎么解决？

### ISSUE THREAD

**Issue by lawlorentz** [Hovennnnn/PKUAutoElective#4]
<img width="903" alt="73b5274a2b968da2c037018282c945a" src="https://github.com/user-attachments/assets/ebdb7eea-1351-4682-a142-6a696308477b">

**Comment by lawlorentz** [comment]
运行一段时间之后就会被拒绝连接

**Comment by ukkaaishan** [comment]
不是很清楚，把interval拉的很长现在也会被识别到，里面具体怎么检测的没人清楚。
不过第二天就把我放出来了lol

**Comment by victinii** [comment]
一样，第一次刷了1个小时被封了，第二次刷了一上午被封了

**Comment by Hovennnnn** [comment]
可能是选课网后台的识别机制提升了，我目前没有遇到这个情况（我设置的interval是6s），可以考虑把时间的随机性调大一点，还有就是客户端的个数。
